### ISSUE TITLE
Ajout du support de Grid Layout

### ISSUE THREAD

**Issue by tzi** [alsacreations/mydevice#17]
Hello !

Merci pour mydevice.io que j'utilise très régulièrement.

Ce serait sympa de rajouter le support de grid layout, afin d'encourager son utilisation.

A plus,
Thomas.

**Comment by raphaelgoetter** [comment]
Merci de me l'avoir rappelé. Ça y est, c'est en ligne.
J'en ai profité pour mettre à jour les différents tests.

**Comment by tzi** [comment]
Top !

Bonne journée :)
